#!/usr/bin/with-contenv sh

do_query() {
    echo "$1" >> /tmp/cmd
  
}

do_exec_query(){
        /usr/bin/mysql </tmp/cmd
        return $?
}


is_db_enabled(){
    NAME="DB_"$COUNTER"_NAME"
    DB_NAME=$(eval 'echo $'$NAME)
    if [ -z "$DB_NAME" ];
    then 
        return 1
    fi

    NAME="DB_"$COUNTER"_PASS"
    DB_PASS=$(eval 'echo $'$NAME)
    if [ -z "$DB_PASS" ];
    then 
        DB_PASS=$ROOT_PASSWORD
    fi
    
    return 0
}

next(){
    echo "> Get Next Site"
    COUNTER=$(($COUNTER + 1))
}

chown mysql:mysql /var/lib/mysql -R

COOKIE=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
sed -i "s;cfg['blowfish_secret'] = '';cfg['blowfish_secret'] = '$COOKIE';g" /etc/phpmyadmin/config.inc.php


COUNTER=0

if [ -z "$(ls -A "/var/lib/mysql")" ];
then
        su - mysql -s /bin/sh -c "mysql_install_db"
        touch /tmp/mariadb
        rm /tmp/cmd

        do_query "DELETE FROM mysql.user WHERE User='';"
        do_query "DELETE FROM mysql.user WHERE User <> 'root';"
        do_query "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1');"
        do_query "DROP DATABASE IF EXISTS test;"
        do_query "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';"
        
        while [ 1 -eq 1 ];
        do    
                if ! is_db_enabled;
                then
                        break
                fi

                do_query "CREATE USER '$DB_NAME'@'%' IDENTIFIED VIA mysql_native_password USING '$DB_PASS';"
                do_query "CREATE DATABASE IF NOT EXISTS $DB_NAME ;"
                do_query "GRANT ALL privileges ON '$DB_NAME'.* TO '$DB_NAME'@'%' ;"
                do_query "GRANT ALL privileges ON '$DB_NAME\_%'.* TO '$DB_NAME'@'%' ;"
                next; 
        done
        
        do_query "FLUSH PRIVILEGES;"
        
        while [ ! $( ls -A "/run/mysqld/mysqld.sock") ];
        do
            sleep 1
        done

        do_exec_query
        mysqladmin -u root password $ROOT_PASSWORD
        sed -i "s;#;;g" /etc/mysql/my.cnf
        sed -i "s;{ROOT_PASSWORD};${ROOT_PASSWORD};g" /etc/mysql/my.cnf

else
        touch /tmp/mariadb
fi